name: tamiz deploy

on:
    push:
        branches:
            - main

jobs: 
    deploy: 
        runs-on: "self-hosted"

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: deploy
              run: | 
                rm -r /home/actions/BrinellCTF
                mkdir /home/actions/BrinellCTF
                cd /home/actions/
                git clone 'https://github.com/PseudoMotivated/BrinellCTF/'
                cd BrinellCTF/frontend 
                npm install
                ls
                