name: tamiz deploy

on:
    push:
        branches:
            - main

jobs: 
    deploy: 
        runs-on: "self-hosted"

        steps:
            - name: Checkout
              uses: actions/checkout@v2